CREATE EXTERNAL TABLE users
(
id int,
name string
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n'
STORED AS TEXTFILE 
LOCATION 's3a://raul-folder/input';


INSERT OVERWRITE DIRECTORY 's3a://raul-folder/output/'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
STORED AS TEXTFILE
SELECT * FROM users;